apiVersion: v1
kind: Service
metadata:
  name: k8s-failure-demo
  labels:
    app: k8s-failure-demo
spec:
  selector:
    app: k8s-failure-demo
  ports:
  - port: 80
    targetPort: 5000
    name: http
  - port: 8000
    targetPort: 8000
    name: metrics
  type: LoadBalancer 